apiVersion: v1
kind: Service
metadata:
  name: todo-webapp-service
  labels:
    app: todo-webapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: todo-webapp 